baseurl = "/"
languageCode = "en-us"
title = "Samuel Calderon"
theme = "hugo-lithium2"
googleAnalytics = "UA-157291344-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Blog"
    url = "/blog/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/calderonsamuel/blog"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/samuel__case"
[[menu.main]]
    name = "Acerca de"
    url = "/about/"

[params]
    description = "Web hecha con el paquete blogdown de R y Hugo"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "240px.png"
    width = 50
    height = 50
    alt = "Logo"

